### ISSUE TITLE
App icon following the GNOME HIG

### ISSUE THREAD

**Issue by bragefuglseth** [leolost2605/Gradebook#11]
Hi! As of now, the icon of this app looks out of place among other GNOME icons. I have created a suggestion for how the icon could look, along with a symbolic. It closely mimics the icon of [GNOME Contacts](https://apps.gnome.org/app/org.gnome.Contacts/).

Primary:
![io github leolost2605 gradebook](https://user-images.githubusercontent.com/91388039/209585001-95b7858e-6a86-49d9-8287-0c389dc86c18.svg)

Devel:
![io github leolost2605 gradebook Devel](https://user-images.githubusercontent.com/91388039/209585039-e75373c7-7154-4ab6-8179-344807edf92a.svg)

Symbolic:
![io github leolost2605 gradebook-symbolic](https://user-images.githubusercontent.com/91388039/209585045-d590eeb1-d455-4fc6-bc10-b7a0268e8064.svg)

I hope this is helpful in some way or another! :grin:

**Comment by ConfusedAlex** [comment]
Damn, this looks fire!

**Comment by leolost2605** [comment]
Hey,
thank you so much for your work! 
The old icon was just a kind of place holder cause i am really not good with design stuff like that :) 
I'll gladly use your new icon if I may.

**Comment by bragefuglseth** [comment]
Of course you can use it, I'm happy to help! :smile:
